## Recitation 1 : 24788 - Introduction to Deep Learning 

## Introduction to Pytorch 

Pytorch is an open source deep learning from Facebook AI. It provides great flexibility for research and is a very popular tool among deep learning practioners. 

#### Installation instruction for pytorch 
https://pytorch.org


#### What is a tensor 
1. Tensors can be thought of as multidimensional arrays
2. You can run tensor operations on a GPU or a CPU  


https://machinelearningmastery.com/introduction-to-tensors-for-machine-learning/

#### Note
The content of this recitation has been inspired from from pytorch's own tutorials on tensors and its operations and 11785 - Introduction to Deep Learning (CMU) - https://deeplearning.cs.cmu.edu/S22/index.html

In [23]:
!nvidia-smi

Fri Jan 20 16:04:22 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| 32%   58C    P2    52W / 250W |   4569MiB / 11177MiB |     26%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [1]:
import torch

In [24]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89


In [2]:
# Check to see if your system has gpu
device = torch.cuda.is_available()
print(device) # prints True if gpu is available, else False

True


### Tensor Creation

In [25]:
t1 = torch.zeros(size=(4,3))  # creates a tensor of Zeros with the given shape     
t2 = torch.ones((4,4))   # creates a tensor of ones with  given shape            
t3 = torch.rand(size=(3,4))   #  creates a tensor of the given shape by uniformly sampling between 0 and 1              

print(t1)
print(t2)
print(t3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.6960, 0.7982, 0.8229, 0.5514],
        [0.2032, 0.1160, 0.4835, 0.5527],
        [0.9358, 0.6476, 0.7183, 0.5918]])


#### Tensor conversion and creation 

In [4]:
import numpy as np

# Pytorch can create a tensor by directly infering the type of data
data_list =  [1,2,3,4]
t1 = torch.tensor(data_list)    # Creating Tensor from a list 

data_arr =  np.array([1,2,3,4]) # Creating a tensor from numpy array
t2 = torch.tensor(data_arr)    

t3 = torch.from_numpy(data_arr) # Creating a tensor from numpy array

t4 = t3.clone()                 # copy from existing torch tensor

print("t1:",t1)
print("t2:",t2)
print("t3:",t3)
print("t4:",t4)


## We can also convert the tensor back to numpy array

a1 = t2.numpy()
print("a1:",a1)


## We can also convert the data types of the tensor 
f1 =  t1.float()

d1 = t1.double()

print("t1 - data type:", t1, t1.dtype)
print("f1 - data type:", f1, f1.dtype)
print("d1 - data type:", d1, d1.dtype)

t1: tensor([1, 2, 3, 4])
t2: tensor([1, 2, 3, 4])
t3: tensor([1, 2, 3, 4])
t4: tensor([1, 2, 3, 4])
a1: [1 2 3 4]
t1 - data type: tensor([1, 2, 3, 4]) torch.int64
f1 - data type: tensor([1., 2., 3., 4.]) torch.float32
d1 - data type: tensor([1., 2., 3., 4.], dtype=torch.float64) torch.float64


In [20]:
d1 + f1

tensor([2., 4., 6., 8.], dtype=torch.float64)

In [21]:
d1_cuda = d1.cuda()

In [22]:
d1_cuda + d1

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

More information on Tensor Conversion : (https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html)

More information on Tensor datatypes: (https://pytorch.org/docs/stable/tensors.html)




### Tensor indexing & Slicing 

In [5]:
# Indexing in tensors is similar to numpy array
t = torch.rand(size=(4,3))

print("Tensor t ",t)
print("Tensor shape", t.shape)

### Accessing the elements in the the tensor is similar to numpy 

print(t[0,0])
print(t[3,2])

## Slicing is also similar to numpy 

print(t[0])
print(t[:2])
print(t[:,2])

Tensor t  tensor([[0.8350, 0.5333, 0.8385],
        [0.6421, 0.5796, 0.3290],
        [0.3277, 0.6140, 0.0450],
        [0.0598, 0.6340, 0.1585]])
Tensor shape torch.Size([4, 3])
tensor(0.8350)
tensor(0.1585)
tensor([0.8350, 0.5333, 0.8385])
tensor([[0.8350, 0.5333, 0.8385],
        [0.6421, 0.5796, 0.3290]])
tensor([0.8385, 0.3290, 0.0450, 0.1585])


### Flatten

In [6]:
t = torch.rand(size=(3,4)) 
print(t) 
print(t.shape)               
print(t.flatten())
print(t.flatten().shape)  

tensor([[0.7764, 0.3575, 0.9771, 0.6942],
        [0.9241, 0.2583, 0.9544, 0.7713],
        [0.1639, 0.3513, 0.6001, 0.5070]])
torch.Size([3, 4])
tensor([0.7764, 0.3575, 0.9771, 0.6942, 0.9241, 0.2583, 0.9544, 0.7713, 0.1639,
        0.3513, 0.6001, 0.5070])
torch.Size([12])


### Reshape the tensors 

In [7]:
print('Orginal tensor shape: ', t.shape)
t_re = t.reshape((2,6))
print(t_re, t_re.shape)


Orginal tensor shape:  torch.Size([3, 4])
tensor([[0.7764, 0.3575, 0.9771, 0.6942, 0.9241, 0.2583],
        [0.9544, 0.7713, 0.1639, 0.3513, 0.6001, 0.5070]]) torch.Size([2, 6])


### Using View operation

The view operation may not work in all cases, you may check the below link to know more about the differences
https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch

In [8]:
print('Orginal tensor shape: ', t.shape)
t_v = t.view((2,6))
print(t_v, t_v.shape)

Orginal tensor shape:  torch.Size([3, 4])
tensor([[0.7764, 0.3575, 0.9771, 0.6942, 0.9241, 0.2583],
        [0.9544, 0.7713, 0.1639, 0.3513, 0.6001, 0.5070]]) torch.Size([2, 6])


### Using the transpose operation 

In [9]:
print('Orginal tensor shape: ', t.shape)
t_t = t.transpose(0,1)
print(t_t, t_t.shape)

Orginal tensor shape:  torch.Size([3, 4])
tensor([[0.7764, 0.9241, 0.1639],
        [0.3575, 0.2583, 0.3513],
        [0.9771, 0.9544, 0.6001],
        [0.6942, 0.7713, 0.5070]]) torch.Size([4, 3])


### Squeeze and Unsqueeze
Squeeze and unsqueeze are especially useful when you want to add a dimension to a tensor. You may have to use them in coding convnets 

In [10]:
#Unsqueeze

print('Orginal tensor shape: ', t.shape)
t_u = t.unsqueeze(dim = 0)
print(t_u, t_u.shape)


Orginal tensor shape:  torch.Size([3, 4])
tensor([[[0.7764, 0.3575, 0.9771, 0.6942],
         [0.9241, 0.2583, 0.9544, 0.7713],
         [0.1639, 0.3513, 0.6001, 0.5070]]]) torch.Size([1, 3, 4])


In [11]:
# Squeeze

print('Unsqueeze tensor shape: ', t_u.shape)
t_s = t_u.squeeze(dim = 0)
print(t_s, t_s.shape)

Unsqueeze tensor shape:  torch.Size([1, 3, 4])
tensor([[0.7764, 0.3575, 0.9771, 0.6942],
        [0.9241, 0.2583, 0.9544, 0.7713],
        [0.1639, 0.3513, 0.6001, 0.5070]]) torch.Size([3, 4])


### Permute Tensor

Permute is especially useful when you have multideimensional array and can be used when we are required to swap axes in the tensors.

For more information on permute, transpose, view, reshape : https://jdhao.github.io/2019/07/10/pytorch_view_reshape_transpose_permute/

In [12]:
t_p = torch.rand(size = (3,4,5))

print("Original tensor shape",t_p.shape)
print(t_p)

print("Permute tensor shape:", t_p.permute(1,0,2).shape)
print(t_p.permute(1,0,2))

Original tensor shape torch.Size([3, 4, 5])
tensor([[[0.0186, 0.4665, 0.7608, 0.7620, 0.6668],
         [0.5883, 0.1197, 0.1325, 0.4239, 0.1412],
         [0.3235, 0.8802, 0.9862, 0.6877, 0.7067],
         [0.0244, 0.0752, 0.3690, 0.6431, 0.9526]],

        [[0.3555, 0.1257, 0.5786, 0.1062, 0.7484],
         [0.6332, 0.8669, 0.3057, 0.5379, 0.1050],
         [0.5895, 0.9318, 0.4647, 0.8507, 0.4045],
         [0.0160, 0.2488, 0.5062, 0.3757, 0.4753]],

        [[0.9061, 0.6909, 0.0712, 0.9085, 0.5604],
         [0.5611, 0.4636, 0.0587, 0.6144, 0.6807],
         [0.7668, 0.1375, 0.3162, 0.9746, 0.9654],
         [0.5562, 0.0900, 0.8455, 0.6676, 0.7922]]])
Permute tensor shape: torch.Size([4, 3, 5])
tensor([[[0.0186, 0.4665, 0.7608, 0.7620, 0.6668],
         [0.3555, 0.1257, 0.5786, 0.1062, 0.7484],
         [0.9061, 0.6909, 0.0712, 0.9085, 0.5604]],

        [[0.5883, 0.1197, 0.1325, 0.4239, 0.1412],
         [0.6332, 0.8669, 0.3057, 0.5379, 0.1050],
         [0.5611, 0.4636, 0.0587, 0.6

### Concatenate

In [26]:
t1 = torch.rand(size=(3,4))
t2 = torch.rand(size=(3,4))

print('Tensor 1:', t1)
print('Tensor 2:', t2)

print('Concatenating two tensors along axis 0')
print(torch.cat([t1,t2],dim=0))
print('New Shape: ', torch.cat([t1,t2],dim=0).shape) ## Row concatenation 

Tensor 1: tensor([[0.6312, 0.2007, 0.9081, 0.1016],
        [0.8234, 0.1749, 0.9035, 0.2749],
        [0.0488, 0.9051, 0.8055, 0.5865]])
Tensor 2: tensor([[0.6168, 0.6756],
        [0.4752, 0.1926],
        [0.2090, 0.4825]])
Concatenating two tensors along axis 0


RuntimeError: Sizes of tensors must match except in dimension 0. Got 4 and 2 in dimension 1 (The offending index is 1)

### Stack

In [14]:
t1 = torch.rand(size=(3,4)) 
t2 = torch.rand(size=(3,4))

print("Tensor 1 shape:", t1.shape)
print(t1)

print("Tensor 2 shape:", t2.shape)
print(t2)

print(torch.stack([t1,t2],dim=0)) #(3, 4) --> (1, 3, 4) --> (N, 3, 4) # stacks along the dimension to insert
print("New Shape:", torch.stack([t1,t2],dim=0).shape, '\n')


Tensor 1 shape: torch.Size([3, 4])
tensor([[0.0728, 0.8283, 0.9617, 0.5129],
        [0.6253, 0.4481, 0.3212, 0.9238],
        [0.6694, 0.6927, 0.7659, 0.4304]])
Tensor 2 shape: torch.Size([3, 4])
tensor([[0.2309, 0.8462, 0.1810, 0.6019],
        [0.5666, 0.4586, 0.2713, 0.5802],
        [0.5136, 0.5027, 0.9454, 0.5232]])
tensor([[[0.0728, 0.8283, 0.9617, 0.5129],
         [0.6253, 0.4481, 0.3212, 0.9238],
         [0.6694, 0.6927, 0.7659, 0.4304]],

        [[0.2309, 0.8462, 0.1810, 0.6019],
         [0.5666, 0.4586, 0.2713, 0.5802],
         [0.5136, 0.5027, 0.9454, 0.5232]]])
New Shape: torch.Size([2, 3, 4]) 



### Computational operations


#### Tensor addition, multiplication

In [15]:
t1 = torch.rand(size = (3,4))
t2 = torch.rand(size = (3,4))

print("Tensor 1", t1)
print("Tensor 2", t2)

Tensor 1 tensor([[0.6054, 0.7673, 0.7317, 0.2100],
        [0.7466, 0.1533, 0.1374, 0.0058],
        [0.6464, 0.9646, 0.1740, 0.3705]])
Tensor 2 tensor([[0.4959, 0.1798, 0.1164, 0.1563],
        [0.7469, 0.8262, 0.7221, 0.4554],
        [0.7212, 0.4184, 0.7196, 0.4577]])


In [16]:
### Adding two tensors
print('t1+t2')
print(t1+t2)

t1+t2
tensor([[1.1013, 0.9470, 0.8481, 0.3663],
        [1.4935, 0.9795, 0.8595, 0.4612],
        [1.3675, 1.3830, 0.8936, 0.8282]])


In [17]:
### multiplying two tensors
print('Element wise multiplication t1*t2')
print(t1*t2)


### If you want to perform matrix multiplication please ensure that the shapes are correct 

print("Matmul t1 @ t2")
print(torch.matmul(t1,t2.T)) ## 3 x 4 @ 4 x 3 --> 3 x 3

Element wise multiplication t1*t2
tensor([[0.3002, 0.1379, 0.0852, 0.0328],
        [0.5576, 0.1267, 0.0992, 0.0026],
        [0.4661, 0.4036, 0.1252, 0.1696]])
Matmul t1 @ t2
tensor([[0.5562, 1.7101, 1.3802],
        [0.4147, 0.7861, 0.7040],
        [0.5721, 1.5741, 1.1645]])


In [18]:
### Scalar operations

print(t1+1)
print(t1*2)

tensor([[1.6054, 1.7673, 1.7317, 1.2100],
        [1.7466, 1.1533, 1.1374, 1.0058],
        [1.6464, 1.9646, 1.1740, 1.3705]])
tensor([[1.2108, 1.5345, 1.4634, 0.4200],
        [1.4931, 0.3066, 0.2747, 0.0116],
        [1.2927, 1.9291, 0.3480, 0.7411]])


#### Other useful operations

In [19]:
t1 = torch.ones(size=(3,4))

print("Tensor1 ", t1)
## sum 

t1_sum = torch.sum(t1, dim =1)
print("Sum", t1_sum)

t1_mean = torch.mean(t1, dim = 0)
print("mean", t1_mean)

t2 = torch.rand(3)
print("Tensor 2", t2)

t2_argmax = torch.argmax(t2)
print("argmax", t2_argmax)

Tensor1  tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Sum tensor([4., 4., 4.])
mean tensor([1., 1., 1., 1.])
Tensor 2 tensor([0.8856, 0.6233, 0.3415])
argmax tensor(0)


#### Explore more about pytorch tensors: https://www.youtube.com/watch?v=r7QDUPb2dCM